version: "3"

services:
  blockchain:
    build: ./blockchain/
    image: blockchain
    container_name: blockchain
    volumes:
      - ./blockchain:/blockchain
    tty: true  # garde le terminal ouvert
