version: "3"

services:
  node:
    build: ./node/ # docker compose cherche un dockerfile dans ce folder pour créer l'image
    image: node
    container_name: node
    volumes:
      - ./node:/node
    command: /bin/bash -c "/node/init.sh && /bin/bash"
    tty: true  # garde le terminal ouvert
